// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/proto/txrelay/v1/txrelay.proto

package txrelayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_proto_txrelay_v1_txrelay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_txrelay_v1_txrelay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_txrelay_v1_txrelay_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_proto_txrelay_v1_txrelay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_txrelay_v1_txrelay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_txrelay_v1_txrelay_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type StreamFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []string               `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Programs      []string               `protobuf:"bytes,2,rep,name=programs,proto3" json:"programs,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"` // "tx" | "log" | "vote" | ""
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamFilter) Reset() {
	*x = StreamFilter{}
	mi := &file_api_proto_txrelay_v1_txrelay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamFilter) ProtoMessage() {}

func (x *StreamFilter) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_txrelay_v1_txrelay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamFilter.ProtoReflect.Descriptor instead.
func (*StreamFilter) Descriptor() ([]byte, []int) {
	return file_api_proto_txrelay_v1_txrelay_proto_rawDescGZIP(), []int{2}
}

func (x *StreamFilter) GetAccounts() []string {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *StreamFilter) GetPrograms() []string {
	if x != nil {
		return x.Programs
	}
	return nil
}

func (x *StreamFilter) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *StreamFilter          `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_api_proto_txrelay_v1_txrelay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_txrelay_v1_txrelay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_txrelay_v1_txrelay_proto_rawDescGZIP(), []int{3}
}

func (x *StreamRequest) GetFilter() *StreamFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`     // tx sig or composite id
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"` // tx/log/vote
	Slot          string                 `protobuf:"bytes,3,opt,name=slot,proto3" json:"slot,omitempty"`
	Account       string                 `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"` // primary actor (optional)
	Program       string                 `protobuf:"bytes,5,opt,name=program,proto3" json:"program,omitempty"`
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"` // raw or JSON bytes
	TsMs          int64                  `protobuf:"varint,7,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_api_proto_txrelay_v1_txrelay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_txrelay_v1_txrelay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_proto_txrelay_v1_txrelay_proto_rawDescGZIP(), []int{4}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Event) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

func (x *Event) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Event) GetProgram() string {
	if x != nil {
		return x.Program
	}
	return ""
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

var File_api_proto_txrelay_v1_txrelay_proto protoreflect.FileDescriptor

const file_api_proto_txrelay_v1_txrelay_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/txrelay/v1/txrelay.proto\x12\n" +
	"txrelay.v1\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"Z\n" +
	"\fStreamFilter\x12\x1a\n" +
	"\baccounts\x18\x01 \x03(\tR\baccounts\x12\x1a\n" +
	"\bprograms\x18\x02 \x03(\tR\bprograms\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\"A\n" +
	"\rStreamRequest\x120\n" +
	"\x06filter\x18\x01 \x01(\v2\x18.txrelay.v1.StreamFilterR\x06filter\"\xa2\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04slot\x18\x03 \x01(\tR\x04slot\x12\x18\n" +
	"\aaccount\x18\x04 \x01(\tR\aaccount\x12\x18\n" +
	"\aprogram\x18\x05 \x01(\tR\aprogram\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12\x13\n" +
	"\x05ts_ms\x18\a \x01(\x03R\x04tsMs2\x85\x01\n" +
	"\bSentinel\x12?\n" +
	"\x06Health\x12\x19.txrelay.v1.HealthRequest\x1a\x1a.txrelay.v1.HealthResponse\x128\n" +
	"\x06Stream\x12\x19.txrelay.v1.StreamRequest\x1a\x11.txrelay.v1.Event0\x01B.Z,solana-sentinel/api/gen/txrelay/v1;txrelayv1b\x06proto3"

var (
	file_api_proto_txrelay_v1_txrelay_proto_rawDescOnce sync.Once
	file_api_proto_txrelay_v1_txrelay_proto_rawDescData []byte
)

func file_api_proto_txrelay_v1_txrelay_proto_rawDescGZIP() []byte {
	file_api_proto_txrelay_v1_txrelay_proto_rawDescOnce.Do(func() {
		file_api_proto_txrelay_v1_txrelay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_txrelay_v1_txrelay_proto_rawDesc), len(file_api_proto_txrelay_v1_txrelay_proto_rawDesc)))
	})
	return file_api_proto_txrelay_v1_txrelay_proto_rawDescData
}

var file_api_proto_txrelay_v1_txrelay_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_txrelay_v1_txrelay_proto_goTypes = []any{
	(*HealthRequest)(nil),  // 0: txrelay.v1.HealthRequest
	(*HealthResponse)(nil), // 1: txrelay.v1.HealthResponse
	(*StreamFilter)(nil),   // 2: txrelay.v1.StreamFilter
	(*StreamRequest)(nil),  // 3: txrelay.v1.StreamRequest
	(*Event)(nil),          // 4: txrelay.v1.Event
}
var file_api_proto_txrelay_v1_txrelay_proto_depIdxs = []int32{
	2, // 0: txrelay.v1.StreamRequest.filter:type_name -> txrelay.v1.StreamFilter
	0, // 1: txrelay.v1.Sentinel.Health:input_type -> txrelay.v1.HealthRequest
	3, // 2: txrelay.v1.Sentinel.Stream:input_type -> txrelay.v1.StreamRequest
	1, // 3: txrelay.v1.Sentinel.Health:output_type -> txrelay.v1.HealthResponse
	4, // 4: txrelay.v1.Sentinel.Stream:output_type -> txrelay.v1.Event
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_txrelay_v1_txrelay_proto_init() }
func file_api_proto_txrelay_v1_txrelay_proto_init() {
	if File_api_proto_txrelay_v1_txrelay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_txrelay_v1_txrelay_proto_rawDesc), len(file_api_proto_txrelay_v1_txrelay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_txrelay_v1_txrelay_proto_goTypes,
		DependencyIndexes: file_api_proto_txrelay_v1_txrelay_proto_depIdxs,
		MessageInfos:      file_api_proto_txrelay_v1_txrelay_proto_msgTypes,
	}.Build()
	File_api_proto_txrelay_v1_txrelay_proto = out.File
	file_api_proto_txrelay_v1_txrelay_proto_goTypes = nil
	file_api_proto_txrelay_v1_txrelay_proto_depIdxs = nil
}
