// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/v1/sentinel.proto

package apiv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkey        string                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountRef) Reset() {
	*x = AccountRef{}
	mi := &file_api_v1_sentinel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRef) ProtoMessage() {}

func (x *AccountRef) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sentinel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRef.ProtoReflect.Descriptor instead.
func (*AccountRef) Descriptor() ([]byte, []int) {
	return file_api_v1_sentinel_proto_rawDescGZIP(), []int{0}
}

func (x *AccountRef) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

type ProgramRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProgramId     string                 `protobuf:"bytes,1,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramRef) Reset() {
	*x = ProgramRef{}
	mi := &file_api_v1_sentinel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramRef) ProtoMessage() {}

func (x *ProgramRef) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sentinel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramRef.ProtoReflect.Descriptor instead.
func (*ProgramRef) Descriptor() ([]byte, []int) {
	return file_api_v1_sentinel_proto_rawDescGZIP(), []int{1}
}

func (x *ProgramRef) GetProgramId() string {
	if x != nil {
		return x.ProgramId
	}
	return ""
}

type SlotRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         uint64                 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End           uint64                 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotRange) Reset() {
	*x = SlotRange{}
	mi := &file_api_v1_sentinel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotRange) ProtoMessage() {}

func (x *SlotRange) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sentinel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotRange.ProtoReflect.Descriptor instead.
func (*SlotRange) Descriptor() ([]byte, []int) {
	return file_api_v1_sentinel_proto_rawDescGZIP(), []int{2}
}

func (x *SlotRange) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *SlotRange) GetEnd() uint64 {
	if x != nil {
		return x.End
	}
	return 0
}

type TxSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     string                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Slot          uint64                 `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	Err           string                 `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	Fee           int64                  `protobuf:"varint,4,opt,name=fee,proto3" json:"fee,omitempty"`
	BlockTimeUnix int64                  `protobuf:"varint,5,opt,name=block_time_unix,json=blockTimeUnix,proto3" json:"block_time_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxSummary) Reset() {
	*x = TxSummary{}
	mi := &file_api_v1_sentinel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxSummary) ProtoMessage() {}

func (x *TxSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sentinel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxSummary.ProtoReflect.Descriptor instead.
func (*TxSummary) Descriptor() ([]byte, []int) {
	return file_api_v1_sentinel_proto_rawDescGZIP(), []int{3}
}

func (x *TxSummary) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *TxSummary) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *TxSummary) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *TxSummary) GetFee() int64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *TxSummary) GetBlockTimeUnix() int64 {
	if x != nil {
		return x.BlockTimeUnix
	}
	return 0
}

type Event struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind           string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Signature      string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Slot           uint64                 `protobuf:"varint,4,opt,name=slot,proto3" json:"slot,omitempty"`
	Account        string                 `protobuf:"bytes,5,opt,name=account,proto3" json:"account,omitempty"`
	Program        string                 `protobuf:"bytes,6,opt,name=program,proto3" json:"program,omitempty"`
	Amount         string                 `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Mint           string                 `protobuf:"bytes,8,opt,name=mint,proto3" json:"mint,omitempty"`
	RawJson        string                 `protobuf:"bytes,9,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	OccurredAtUnix int64                  `protobuf:"varint,10,opt,name=occurred_at_unix,json=occurredAtUnix,proto3" json:"occurred_at_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_api_v1_sentinel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sentinel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_v1_sentinel_proto_rawDescGZIP(), []int{4}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Event) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Event) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *Event) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Event) GetProgram() string {
	if x != nil {
		return x.Program
	}
	return ""
}

func (x *Event) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Event) GetMint() string {
	if x != nil {
		return x.Mint
	}
	return ""
}

func (x *Event) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

func (x *Event) GetOccurredAtUnix() int64 {
	if x != nil {
		return x.OccurredAtUnix
	}
	return 0
}

type GetTxsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Scope:
	//
	//	*GetTxsRequest_Account
	//	*GetTxsRequest_Program
	Scope         isGetTxsRequest_Scope `protobuf_oneof:"scope"`
	Slots         *SlotRange            `protobuf:"bytes,3,opt,name=slots,proto3" json:"slots,omitempty"`  // query: slots.start=..&slots.end=..
	Limit         uint32                `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"` // query: limit=
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTxsRequest) Reset() {
	*x = GetTxsRequest{}
	mi := &file_api_v1_sentinel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTxsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTxsRequest) ProtoMessage() {}

func (x *GetTxsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sentinel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTxsRequest.ProtoReflect.Descriptor instead.
func (*GetTxsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sentinel_proto_rawDescGZIP(), []int{5}
}

func (x *GetTxsRequest) GetScope() isGetTxsRequest_Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *GetTxsRequest) GetAccount() *AccountRef {
	if x != nil {
		if x, ok := x.Scope.(*GetTxsRequest_Account); ok {
			return x.Account
		}
	}
	return nil
}

func (x *GetTxsRequest) GetProgram() *ProgramRef {
	if x != nil {
		if x, ok := x.Scope.(*GetTxsRequest_Program); ok {
			return x.Program
		}
	}
	return nil
}

func (x *GetTxsRequest) GetSlots() *SlotRange {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *GetTxsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type isGetTxsRequest_Scope interface {
	isGetTxsRequest_Scope()
}

type GetTxsRequest_Account struct {
	Account *AccountRef `protobuf:"bytes,1,opt,name=account,proto3,oneof"` // query: account.pubkey=...
}

type GetTxsRequest_Program struct {
	Program *ProgramRef `protobuf:"bytes,2,opt,name=program,proto3,oneof"` // query: program.program_id=...
}

func (*GetTxsRequest_Account) isGetTxsRequest_Scope() {}

func (*GetTxsRequest_Program) isGetTxsRequest_Scope() {}

type GetTxsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txs           []*TxSummary           `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTxsResponse) Reset() {
	*x = GetTxsResponse{}
	mi := &file_api_v1_sentinel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTxsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTxsResponse) ProtoMessage() {}

func (x *GetTxsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sentinel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTxsResponse.ProtoReflect.Descriptor instead.
func (*GetTxsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_sentinel_proto_rawDescGZIP(), []int{6}
}

func (x *GetTxsResponse) GetTxs() []*TxSummary {
	if x != nil {
		return x.Txs
	}
	return nil
}

type StreamEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Scope:
	//
	//	*StreamEventsRequest_Account
	//	*StreamEventsRequest_Program
	Scope         isStreamEventsRequest_Scope `protobuf_oneof:"scope"`
	FilterKind    string                      `protobuf:"bytes,3,opt,name=filter_kind,json=filterKind,proto3" json:"filter_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_api_v1_sentinel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sentinel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sentinel_proto_rawDescGZIP(), []int{7}
}

func (x *StreamEventsRequest) GetScope() isStreamEventsRequest_Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *StreamEventsRequest) GetAccount() *AccountRef {
	if x != nil {
		if x, ok := x.Scope.(*StreamEventsRequest_Account); ok {
			return x.Account
		}
	}
	return nil
}

func (x *StreamEventsRequest) GetProgram() *ProgramRef {
	if x != nil {
		if x, ok := x.Scope.(*StreamEventsRequest_Program); ok {
			return x.Program
		}
	}
	return nil
}

func (x *StreamEventsRequest) GetFilterKind() string {
	if x != nil {
		return x.FilterKind
	}
	return ""
}

type isStreamEventsRequest_Scope interface {
	isStreamEventsRequest_Scope()
}

type StreamEventsRequest_Account struct {
	Account *AccountRef `protobuf:"bytes,1,opt,name=account,proto3,oneof"`
}

type StreamEventsRequest_Program struct {
	Program *ProgramRef `protobuf:"bytes,2,opt,name=program,proto3,oneof"`
}

func (*StreamEventsRequest_Account) isStreamEventsRequest_Scope() {}

func (*StreamEventsRequest_Program) isStreamEventsRequest_Scope() {}

var File_api_v1_sentinel_proto protoreflect.FileDescriptor

const file_api_v1_sentinel_proto_rawDesc = "" +
	"\n" +
	"\x15api/v1/sentinel.proto\x12\vsentinel.v1\x1a\x1cgoogle/api/annotations.proto\"$\n" +
	"\n" +
	"AccountRef\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\tR\x06pubkey\"+\n" +
	"\n" +
	"ProgramRef\x12\x1d\n" +
	"\n" +
	"program_id\x18\x01 \x01(\tR\tprogramId\"3\n" +
	"\tSlotRange\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x04R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x04R\x03end\"\x89\x01\n" +
	"\tTxSummary\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\tR\tsignature\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\x04R\x04slot\x12\x10\n" +
	"\x03err\x18\x03 \x01(\tR\x03err\x12\x10\n" +
	"\x03fee\x18\x04 \x01(\x03R\x03fee\x12&\n" +
	"\x0fblock_time_unix\x18\x05 \x01(\x03R\rblockTimeUnix\"\x82\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\x12\x12\n" +
	"\x04slot\x18\x04 \x01(\x04R\x04slot\x12\x18\n" +
	"\aaccount\x18\x05 \x01(\tR\aaccount\x12\x18\n" +
	"\aprogram\x18\x06 \x01(\tR\aprogram\x12\x16\n" +
	"\x06amount\x18\a \x01(\tR\x06amount\x12\x12\n" +
	"\x04mint\x18\b \x01(\tR\x04mint\x12\x19\n" +
	"\braw_json\x18\t \x01(\tR\arawJson\x12(\n" +
	"\x10occurred_at_unix\x18\n" +
	" \x01(\x03R\x0eoccurredAtUnix\"\xc6\x01\n" +
	"\rGetTxsRequest\x123\n" +
	"\aaccount\x18\x01 \x01(\v2\x17.sentinel.v1.AccountRefH\x00R\aaccount\x123\n" +
	"\aprogram\x18\x02 \x01(\v2\x17.sentinel.v1.ProgramRefH\x00R\aprogram\x12,\n" +
	"\x05slots\x18\x03 \x01(\v2\x16.sentinel.v1.SlotRangeR\x05slots\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\rR\x05limitB\a\n" +
	"\x05scope\":\n" +
	"\x0eGetTxsResponse\x12(\n" +
	"\x03txs\x18\x01 \x03(\v2\x16.sentinel.v1.TxSummaryR\x03txs\"\xa9\x01\n" +
	"\x13StreamEventsRequest\x123\n" +
	"\aaccount\x18\x01 \x01(\v2\x17.sentinel.v1.AccountRefH\x00R\aaccount\x123\n" +
	"\aprogram\x18\x02 \x01(\v2\x17.sentinel.v1.ProgramRefH\x00R\aprogram\x12\x1f\n" +
	"\vfilter_kind\x18\x03 \x01(\tR\n" +
	"filterKindB\a\n" +
	"\x05scope2\xda\x01\n" +
	"\x0fSentinelService\x12d\n" +
	"\x0fGetTransactions\x12\x1a.sentinel.v1.GetTxsRequest\x1a\x1b.sentinel.v1.GetTxsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/transactions\x12a\n" +
	"\fStreamEvents\x12 .sentinel.v1.StreamEventsRequest\x1a\x12.sentinel.v1.Event\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/stream/events0\x01B\x1eZ\x1csolana-sentinel/api/v1;apiv1b\x06proto3"

var (
	file_api_v1_sentinel_proto_rawDescOnce sync.Once
	file_api_v1_sentinel_proto_rawDescData []byte
)

func file_api_v1_sentinel_proto_rawDescGZIP() []byte {
	file_api_v1_sentinel_proto_rawDescOnce.Do(func() {
		file_api_v1_sentinel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_sentinel_proto_rawDesc), len(file_api_v1_sentinel_proto_rawDesc)))
	})
	return file_api_v1_sentinel_proto_rawDescData
}

var file_api_v1_sentinel_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_v1_sentinel_proto_goTypes = []any{
	(*AccountRef)(nil),          // 0: sentinel.v1.AccountRef
	(*ProgramRef)(nil),          // 1: sentinel.v1.ProgramRef
	(*SlotRange)(nil),           // 2: sentinel.v1.SlotRange
	(*TxSummary)(nil),           // 3: sentinel.v1.TxSummary
	(*Event)(nil),               // 4: sentinel.v1.Event
	(*GetTxsRequest)(nil),       // 5: sentinel.v1.GetTxsRequest
	(*GetTxsResponse)(nil),      // 6: sentinel.v1.GetTxsResponse
	(*StreamEventsRequest)(nil), // 7: sentinel.v1.StreamEventsRequest
}
var file_api_v1_sentinel_proto_depIdxs = []int32{
	0, // 0: sentinel.v1.GetTxsRequest.account:type_name -> sentinel.v1.AccountRef
	1, // 1: sentinel.v1.GetTxsRequest.program:type_name -> sentinel.v1.ProgramRef
	2, // 2: sentinel.v1.GetTxsRequest.slots:type_name -> sentinel.v1.SlotRange
	3, // 3: sentinel.v1.GetTxsResponse.txs:type_name -> sentinel.v1.TxSummary
	0, // 4: sentinel.v1.StreamEventsRequest.account:type_name -> sentinel.v1.AccountRef
	1, // 5: sentinel.v1.StreamEventsRequest.program:type_name -> sentinel.v1.ProgramRef
	5, // 6: sentinel.v1.SentinelService.GetTransactions:input_type -> sentinel.v1.GetTxsRequest
	7, // 7: sentinel.v1.SentinelService.StreamEvents:input_type -> sentinel.v1.StreamEventsRequest
	6, // 8: sentinel.v1.SentinelService.GetTransactions:output_type -> sentinel.v1.GetTxsResponse
	4, // 9: sentinel.v1.SentinelService.StreamEvents:output_type -> sentinel.v1.Event
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_v1_sentinel_proto_init() }
func file_api_v1_sentinel_proto_init() {
	if File_api_v1_sentinel_proto != nil {
		return
	}
	file_api_v1_sentinel_proto_msgTypes[5].OneofWrappers = []any{
		(*GetTxsRequest_Account)(nil),
		(*GetTxsRequest_Program)(nil),
	}
	file_api_v1_sentinel_proto_msgTypes[7].OneofWrappers = []any{
		(*StreamEventsRequest_Account)(nil),
		(*StreamEventsRequest_Program)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_sentinel_proto_rawDesc), len(file_api_v1_sentinel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_sentinel_proto_goTypes,
		DependencyIndexes: file_api_v1_sentinel_proto_depIdxs,
		MessageInfos:      file_api_v1_sentinel_proto_msgTypes,
	}.Build()
	File_api_v1_sentinel_proto = out.File
	file_api_v1_sentinel_proto_goTypes = nil
	file_api_v1_sentinel_proto_depIdxs = nil
}
